### PR TITLE
Rename to loquat

### PR DESCRIPTION
**Pull request by laughedelic**

### CODE REVIEW

**Comment by laughedelic** [comment]
@eparejatobes when I try to move it, I get an error:

> ohnosequences already has a repository in the ohnosequences/nispero network

I guess, same org cannot have a fork of its own repo. We can merge it into nispero though..

**Comment by eparejatobes** [comment]
Mmm. Deleting, creating and pushing? Just pushing everything to a new repo?

**Comment by laughedelic** [comment]
Not like :-1:

**Comment by eparejatobes** [comment]
Alternatives? You can contact github, they probably can unfork it

**Comment by laughedelic** [comment]
Ok, I just created a new repo and changed remote address :ok_hand:

**Pull request merged**
